apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mariadb-restore
  namespace: demo
spec:
  task:
<<<<<<< HEAD
    name: mariadb-restore-v2021.03.08
=======
    name: mariadb-restore-10.5.8
>>>>>>> Update MariaDB image version from 10.5 to 10.5.8
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mariadb
  rules:
  - snapshots: [latest]
